// <auto-generated />
using System;
using EF03KHOAHOCAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF03KHOAHOCAPI.Migrations
{
    [DbContext(typeof(KhoaHocContext))]
    partial class KhoaHocContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF03KHOAHOCAPI.Entites.HocVien", b =>
                {
                    b.Property<int>("HocvienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Quequan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HocvienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("EF03KHOAHOCAPI.Entites.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hocphi")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaybatdau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaykethuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("KhoaHocId");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("EF03KHOAHOCAPI.Entites.NgayHoc", b =>
                {
                    b.Property<int>("NgayhocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NgayhocId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("NgayHocs");
                });

            modelBuilder.Entity("EF03KHOAHOCAPI.Entites.HocVien", b =>
                {
                    b.HasOne("EF03KHOAHOCAPI.Entites.KhoaHoc", "KhoaHocs")
                        .WithMany("HocViens")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("EF03KHOAHOCAPI.Entites.NgayHoc", b =>
                {
                    b.HasOne("EF03KHOAHOCAPI.Entites.KhoaHoc", "KhoaHoc")
                        .WithMany("NgayHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("EF03KHOAHOCAPI.Entites.KhoaHoc", b =>
                {
                    b.Navigation("HocViens");

                    b.Navigation("NgayHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
