// <auto-generated />
using System;
using APIENDGAME.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIENDGAME.Migrations
{
    [DbContext(typeof(HocVienContext))]
    [Migration("20220922095648_hocvien")]
    partial class hocvien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIENDGAME.Entities.BaiViet", b =>
                {
                    b.Property<int>("BaiVietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChuDeID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungNgan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TacGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<string>("TenBaiViet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("date");

                    b.HasKey("BaiVietID");

                    b.HasIndex("ChuDeID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("APIENDGAME.Entities.ChuDe", b =>
                {
                    b.Property<int>("ChuDeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LoaiBaiVietID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChuDeID");

                    b.HasIndex("LoaiBaiVietID");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("APIENDGAME.Entities.DangKyHoc", b =>
                {
                    b.Property<int>("DangKyHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("TaiKhoaID")
                        .HasColumnType("int");

                    b.Property<int?>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<int>("TinhTrangHocID")
                        .HasColumnType("int");

                    b.HasKey("DangKyHocID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("KhoaHocID");

                    b.HasIndex("TaiKhoanID");

                    b.HasIndex("TinhTrangHocID");

                    b.ToTable("DangKyHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.HocVien", b =>
                {
                    b.Property<int>("HocVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("SoNha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HocVienID");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("APIENDGAME.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HocPhi")
                        .HasColumnType("real");

                    b.Property<int>("LoaiKhoaHocID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoHocVien")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongMon")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.HasKey("KhoaHocID");

                    b.HasIndex("LoaiKhoaHocID");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.LoaiBaiViet", b =>
                {
                    b.Property<int>("LoaiBaiVietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoaiBaiVietID");

                    b.ToTable("LoaiBaiViets");
                });

            modelBuilder.Entity("APIENDGAME.Entities.LoaiKhoaHoc", b =>
                {
                    b.Property<int>("LoaiKhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("LoaiKhoaHocID");

                    b.ToTable("LoaiKhoaHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.QuyenHan", b =>
                {
                    b.Property<int>("QuyenHanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenQuyenHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuyenHanID");

                    b.ToTable("QuyenHans");
                });

            modelBuilder.Entity("APIENDGAME.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuyenHanID")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("QuyenHanID");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("APIENDGAME.Entities.TinhTrangHoc", b =>
                {
                    b.Property<int>("TinhTrangHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTinhTrang")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TinhTrangHocID");

                    b.ToTable("TinhTrangHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.BaiViet", b =>
                {
                    b.HasOne("APIENDGAME.Entities.ChuDe", "ChuDe")
                        .WithMany("BaiViets")
                        .HasForeignKey("ChuDeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIENDGAME.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("APIENDGAME.Entities.ChuDe", b =>
                {
                    b.HasOne("APIENDGAME.Entities.LoaiBaiViet", "LoaiBaiViet")
                        .WithMany("ChuDes")
                        .HasForeignKey("LoaiBaiVietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBaiViet");
                });

            modelBuilder.Entity("APIENDGAME.Entities.DangKyHoc", b =>
                {
                    b.HasOne("APIENDGAME.Entities.HocVien", "HocVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("HocVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIENDGAME.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("KhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIENDGAME.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("TaiKhoanID");

                    b.HasOne("APIENDGAME.Entities.TinhTrangHoc", "TinhTrangHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("TinhTrangHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TinhTrangHoc");
                });

            modelBuilder.Entity("APIENDGAME.Entities.KhoaHoc", b =>
                {
                    b.HasOne("APIENDGAME.Entities.LoaiKhoaHoc", "LoaiKhoaHoc")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("LoaiKhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKhoaHoc");
                });

            modelBuilder.Entity("APIENDGAME.Entities.TaiKhoan", b =>
                {
                    b.HasOne("APIENDGAME.Entities.QuyenHan", "QuyenHan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("QuyenHanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyenHan");
                });

            modelBuilder.Entity("APIENDGAME.Entities.ChuDe", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("APIENDGAME.Entities.HocVien", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.KhoaHoc", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.LoaiBaiViet", b =>
                {
                    b.Navigation("ChuDes");
                });

            modelBuilder.Entity("APIENDGAME.Entities.LoaiKhoaHoc", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.QuyenHan", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("APIENDGAME.Entities.TaiKhoan", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("APIENDGAME.Entities.TinhTrangHoc", b =>
                {
                    b.Navigation("DangKyHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
